Resources:
    Ec2Instance:
     Type: 'AWS::EC2::Instance'
     Properties:
       SecurityGroups:
         - !Ref InstanceSecurityGroup
       # The name of the key pair
       KeyName: udacity-devops-default
       # You may need to find out what instance types are
       # available in your region
       # - use https://cloud-images.ubuntu.com/locator/ec2/
       ImageId: 'ami-0d382e80be7ffdae5'
    InstanceSecurityGroup:
     Type: 'AWS::EC2::SecurityGroup'
     Properties:
       GroupDescription: Enable SSH access via port 22
       SecurityGroupIngress:
         - IpProtocol: tcp
           FromPort: '22'
           ToPort: '22'
           CidrIp: 0.0.0.0/0
